query getAgency2CustomerById($customerId: ID!) {
  getAgency2CustomerById(id: $customerId) {
  	id
    givenName
    familyName
    dateOfBirth 
    lastUpdated
    email
    personIdentity {
      identifiers {
        agencyId
        customerId
      }
    }

    currentAddress {
      address1
      address2
      address3
      address4
      state
      postCode
      lastUpdated
    } 
    previousAddresses {
      address1
      address2
      address3
      address4
      state
      postCode
      lastUpdated
      agencyId
    } 
  }
    
}